import Link from "next/link";
import { redirect } from "next/navigation";
import { canViewDesignEngineering, getOrCreateProfile } from "@/lib/permissions";
import { CLIENT_CONFIG } from "@/lib/client-config";
import {
  getDesignProjectStats,
  listMyDesignProjects,
} from "../actions";

export const dynamic = "force-dynamic";

export const metadata = {
  title: `Software (Stage 1) — ${CLIENT_CONFIG.name}`,
};

// Stage 1 catalog + live dashboard. Pulls real numbers from the project
// table so the user sees their own usage, not a marketing brochure.

const MODULES_1 = [
  {
    id: "1a",
    title: "Single-Part 3D→2D MVP",
    status: "live" as const,
    blurb:
      "Upload a part, edit dimensions, accept AI tolerances, download regenerated PDF/DXF/STEP.",
    link: "/design-engineering",
    linkLabel: "Try it · Projects",
  },
  {
    id: "1b",
    title: "Assemblies + BOM",
    status: "live" as const,
    blurb:
      "Multi-part BOM editor with auto-extract from STEP — quantities inferred from the assembly tree.",
    link: "/design-engineering",
    linkLabel: "Try it · Projects",
  },
  {
    id: "1c",
    title: "AI Installation Manuals",
    status: "coming-soon" as const,
    blurb:
      "Interactive 3D + printable PDF + narrated MP4 video. Mate-graph analysis drives step order.",
  },
  {
    id: "1d",
    title: "Engineering Toolkit",
    status: "coming-soon" as const,
    blurb:
      "14 modules — topology optimization, mass props, tolerance stack-up, cost estimator, sustainability.",
  },
  {
    id: "1e",
    title: "AI Tools (Copilot · Chatbot · DFM)",
    status: "partial" as const,
    blurb:
      "Material/process recommender ships today via Claude inside Projects · Step 4. Copilot + DFM scorecard coming.",
    link: "/design-engineering",
    linkLabel: "Try the recommender",
  },
  {
    id: "1f",
    title: "PDM-Lite",
    status: "coming-soon" as const,
    blurb:
      "Vault, versioning, branching, real-time collab (Yjs CRDT), comment threads, permissions.",
  },
  {
    id: "1g",
    title: "Browser CAD + Text-to-CAD",
    status: "coming-soon" as const,
    blurb:
      "Onshape-style WASM parametric modeler. AI text-to-CAD with iterative action-catalog refinement.",
  },
  {
    id: "1h",
    title: "FEA & CFD Validation",
    status: "coming-soon" as const,
    blurb:
      "Auto-meshed structural / modal / fatigue / thermal / CFD. AI-inferred fixtures + loads.",
  },
  {
    id: "1i",
    title: "Marketing Renders",
    status: "coming-soon" as const,
    blurb:
      "PBR materials + HDRi library. AI-generated by mood OR AI-modified swatches.",
  },
  {
    id: "1j",
    title: "Cross-CAD Plugins (Light)",
    status: "coming-soon" as const,
    blurb:
      "Macro AI generation, automation marketplace, ME Expert RAG over Shigley/Roark/ASME.",
  },
];

function StatusPill({ status }: { status: "live" | "partial" | "coming-soon" }) {
  const m = {
    live: {
      label: "Live",
      bg: "rgba(34,197,94,0.16)",
      fg: "rgb(22,163,74)",
    },
    partial: {
      label: "Partial",
      bg: "rgba(234,179,8,0.18)",
      fg: "rgb(161,98,7)",
    },
    "coming-soon": {
      label: "Coming soon",
      bg: "rgba(234,88,12,0.14)",
      fg: "rgb(234,88,12)",
    },
  }[status];
  return (
    <span
      style={{
        background: m.bg,
        color: m.fg,
        padding: "2px 8px",
        borderRadius: 6,
        fontSize: 10,
        fontWeight: 800,
        letterSpacing: 0.8,
        textTransform: "uppercase",
      }}
    >
      {m.label}
    </span>
  );
}

function fmtBytes(b: number) {
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  if (b < 1024 * 1024 * 1024) return `${(b / 1024 / 1024).toFixed(1)} MB`;
  return `${(b / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

export default async function SoftwareModulePage() {
  const profile = await getOrCreateProfile();
  if (!profile) redirect("/sign-in");
  if (!canViewDesignEngineering(profile)) redirect("/");

  const [stats, projects] = await Promise.all([
    getDesignProjectStats(),
    listMyDesignProjects(),
  ]);
  const recent = projects.slice(0, 5);

  return (
    <div
      style={{
        background: "var(--lb-bg)",
        color: "var(--lb-text)",
        minHeight: "100%",
        padding: 24,
        display: "flex",
        flexDirection: "column",
        gap: 20,
      }}
    >
      {/* HERO */}
      <header
        style={{
          padding: "24px 28px",
          borderRadius: 14,
          background:
            "linear-gradient(155deg, rgba(37,99,235,0.10), var(--lb-bg-elev))",
          border: "1px solid rgba(37,99,235,0.28)",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            marginBottom: 8,
          }}
        >
          <span
            style={{
              background: "#2563eb",
              color: "#fff",
              fontSize: 10.5,
              fontWeight: 800,
              letterSpacing: 1.2,
              padding: "3px 10px",
              borderRadius: 5,
              textTransform: "uppercase",
            }}
          >
            Stage 1 · Software
          </span>
        </div>
        <h1
          style={{
            fontSize: "clamp(28px, 3.6vw, 42px)",
            fontWeight: 800,
            letterSpacing: "-0.025em",
            margin: 0,
            lineHeight: 1.1,
          }}
        >
          The CAD-to-Package Software Suite
        </h1>
        <p
          style={{
            fontSize: 15,
            lineHeight: 1.55,
            color: "var(--lb-text-2)",
            margin: "12px 0 0",
            maxWidth: 760,
          }}
        >
          Ten sub-modules covering everything from drawing generation to FEA,
          assembly manuals, and marketing renders. The Projects workflow is the
          live entry point — every other module plugs in as it ships.
        </p>
      </header>

      {/* STATS */}
      <section
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
          gap: 10,
        }}
      >
        <Stat label="Projects" value={stats.totalProjects} />
        <Stat label="Drafts" value={stats.drafts} />
        <Stat label="Approved" value={stats.approved} />
        <Stat label="CAD files" value={stats.totalCadFiles} />
        <Stat label="BOM lines" value={stats.totalBomLines} />
        <Stat
          label="CAD storage"
          value={fmtBytes(stats.totalCadBytes)}
          isText
        />
      </section>

      {/* QUICK ACTIONS */}
      <section
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
          gap: 10,
        }}
      >
        <ActionCard
          href="/design-engineering"
          accent="#2563eb"
          title="Start a new project"
          blurb="Upload CAD → auto-BOM → AI material rec → approve & export."
          icon="+"
        />
        <ActionCard
          href="/design-engineering/full-cad"
          accent="#ea580c"
          title="Browse Stage 5 CAD modules"
          blurb="Surfacing, CAM, electrical, routing — the advanced suite."
          icon="◊"
        />
        <ActionCard
          href="/design-engineering/enterprise-pdm"
          accent="#7c3aed"
          title="Open the CAD vault"
          blurb="Every CAD file across every project, searchable in one place."
          icon="🗄"
        />
      </section>

      {/* RECENT PROJECTS */}
      <section
        style={{
          padding: "18px 22px",
          borderRadius: 14,
          background: "var(--lb-bg-elev)",
          border: "1px solid var(--lb-border)",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            marginBottom: 12,
          }}
        >
          <h2
            style={{
              fontSize: 14,
              fontWeight: 700,
              margin: 0,
              letterSpacing: "-0.01em",
            }}
          >
            Recent projects
          </h2>
          <Link
            href="/design-engineering"
            style={{
              fontSize: 12.5,
              color: "var(--lb-accent)",
              fontWeight: 600,
              textDecoration: "none",
            }}
          >
            All projects →
          </Link>
        </div>
        {recent.length === 0 ? (
          <div
            style={{
              padding: "24px 20px",
              borderRadius: 10,
              border: "1px dashed var(--lb-border)",
              textAlign: "center",
              color: "var(--lb-text-2)",
              fontSize: 13,
            }}
          >
            No projects yet. Head to{" "}
            <Link
              href="/design-engineering"
              style={{ color: "var(--lb-accent)", fontWeight: 600 }}
            >
              Projects
            </Link>{" "}
            to start one.
          </div>
        ) : (
          <ul
            style={{
              listStyle: "none",
              padding: 0,
              margin: 0,
              display: "flex",
              flexDirection: "column",
              gap: 6,
            }}
          >
            {recent.map((p) => (
              <li key={p.id}>
                <Link
                  href={`/design-engineering/projects/${p.id}`}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 12,
                    padding: "10px 14px",
                    borderRadius: 10,
                    background: "var(--lb-bg)",
                    border: "1px solid var(--lb-border)",
                    textDecoration: "none",
                    color: "inherit",
                  }}
                >
                  <span
                    style={{
                      flex: 1,
                      fontWeight: 600,
                      fontSize: 13.5,
                    }}
                  >
                    {p.name}
                  </span>
                  <span
                    style={{
                      fontSize: 11.5,
                      color: "var(--lb-text-3)",
                    }}
                  >
                    {p.cadFiles.length} CAD · {p.bomItems.length} BOM
                  </span>
                  <span
                    style={{
                      fontSize: 10,
                      fontWeight: 800,
                      letterSpacing: 0.8,
                      padding: "2px 8px",
                      borderRadius: 5,
                      background:
                        p.status === "approved"
                          ? "rgba(34,197,94,0.18)"
                          : "rgba(120,113,108,0.16)",
                      color:
                        p.status === "approved"
                          ? "rgb(22,163,74)"
                          : "rgb(87,83,78)",
                      textTransform: "uppercase",
                    }}
                  >
                    {p.status}
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* MODULE CATALOG */}
      <section
        style={{
          padding: "20px 24px",
          borderRadius: 14,
          background: "var(--lb-bg-elev)",
          border: "1px solid var(--lb-border)",
        }}
      >
        <h2
          style={{
            fontSize: 15,
            fontWeight: 700,
            margin: "0 0 14px",
            letterSpacing: "-0.01em",
          }}
        >
          Sub-module catalog · Stage 1
        </h2>
        <ul
          style={{
            listStyle: "none",
            padding: 0,
            margin: 0,
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
            gap: 10,
          }}
        >
          {MODULES_1.map((m) => (
            <li
              key={m.id}
              style={{
                padding: "14px 16px",
                borderRadius: 10,
                background: "var(--lb-bg)",
                border: "1px solid var(--lb-border)",
                display: "flex",
                flexDirection: "column",
                gap: 6,
              }}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  gap: 8,
                }}
              >
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                  }}
                >
                  <span
                    style={{
                      fontFamily:
                        "ui-monospace, 'JetBrains Mono', Menlo, monospace",
                      fontSize: 11,
                      fontWeight: 800,
                      color: "var(--lb-text-3)",
                      padding: "2px 6px",
                      borderRadius: 5,
                      background: "var(--lb-bg-elev)",
                    }}
                  >
                    {m.id}
                  </span>
                  <h3
                    style={{
                      fontSize: 14,
                      fontWeight: 700,
                      margin: 0,
                      letterSpacing: "-0.01em",
                    }}
                  >
                    {m.title}
                  </h3>
                </div>
                <StatusPill status={m.status} />
              </div>
              <p
                style={{
                  fontSize: 12.5,
                  color: "var(--lb-text-2)",
                  lineHeight: 1.5,
                  margin: 0,
                }}
              >
                {m.blurb}
              </p>
              {m.link && (
                <Link
                  href={m.link}
                  style={{
                    marginTop: 4,
                    fontSize: 12,
                    color: "var(--lb-accent)",
                    fontWeight: 600,
                    textDecoration: "none",
                  }}
                >
                  {m.linkLabel ?? "Open"} →
                </Link>
              )}
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}

function Stat({
  label,
  value,
  isText,
}: {
  label: string;
  value: number | string;
  isText?: boolean;
}) {
  return (
    <div
      style={{
        padding: "14px 16px",
        borderRadius: 12,
        background: "var(--lb-bg-elev)",
        border: "1px solid var(--lb-border)",
      }}
    >
      <div
        style={{
          fontSize: 10,
          fontWeight: 800,
          letterSpacing: 1,
          textTransform: "uppercase",
          color: "var(--lb-text-3)",
        }}
      >
        {label}
      </div>
      <div
        style={{
          fontSize: isText ? 18 : 26,
          fontWeight: 800,
          color: "var(--lb-text)",
          marginTop: 4,
          letterSpacing: "-0.02em",
        }}
      >
        {value}
      </div>
    </div>
  );
}

function ActionCard({
  href,
  accent,
  title,
  blurb,
  icon,
}: {
  href: string;
  accent: string;
  title: string;
  blurb: string;
  icon: string;
}) {
  return (
    <Link
      href={href}
      style={{
        display: "flex",
        gap: 12,
        padding: "16px 18px",
        borderRadius: 12,
        background: "var(--lb-bg-elev)",
        border: "1px solid var(--lb-border)",
        textDecoration: "none",
        color: "inherit",
        transition: "border-color 160ms ease",
      }}
    >
      <span
        aria-hidden
        style={{
          flexShrink: 0,
          width: 36,
          height: 36,
          borderRadius: 9,
          background: accent,
          color: "#fff",
          fontWeight: 800,
          fontSize: 18,
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        {icon}
      </span>
      <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
        <span style={{ fontSize: 14, fontWeight: 700, letterSpacing: "-0.01em" }}>
          {title}
        </span>
        <span style={{ fontSize: 12, color: "var(--lb-text-2)", lineHeight: 1.5 }}>
          {blurb}
        </span>
      </div>
    </Link>
  );
}
